- name: Copy pull secrets
  copy:
      dest: "{{dev_scripts_path}}/pull_secret.json"
      src: pull-secrets.json
- name: Get username
  command: whoami
  changed_when: false
  become: no
  register: whoami
- name: Configure dev-scripts
  copy:
      dest: "{{dev_scripts_path}}/config_{{whoami.stdout}}.sh"
      src: "{{config_file[method]}}"
  register: dev_scripts_config
- name: Set CI token
  blockinfile:
      path: "{{dev_scripts_config.dest}}"
      marker: "# {mark} CI TOKEN BLOCK"
      validate: bash -e %s
      block: |
          # Set the CI token in the file "ci_token"
          set +x
          export CI_TOKEN='{{ lookup('file', 'ci_token') }}'
          set -x
- name: Clear cluster-bot override
  blockinfile:
      path: "{{dev_scripts_config.dest}}"
      marker: "# {mark} CLUSTERBOT OVERRIDE BLOCK"
      validate: bash -e %s
      block: ""
  when: clusterbot_build_id == ""
- name: Set cluster-bot override
  blockinfile:
      path: "{{dev_scripts_config.dest}}"
      marker: "# {mark} CLUSTERBOT OVERRIDE BLOCK"
      validate: bash -e %s
      block: |
          # Set the CI token in the file "clusterbot-ci_token"
          set +x
          export CI_TOKEN='{{ lookup('file', 'clusterbot-ci_token') }}'
          set -x
          export CI_SERVER="api.{{clusterbot_build_server_api}}"
          export OPENSHIFT_RELEASE_IMAGE="registry.{{clusterbot_build_server}}.ci.openshift.org/ci-ln-{{clusterbot_build_id}}/release:latest"
  when: clusterbot_build_id != ""
